name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install Backend Dependencies
    - name: Install Backend Dependencies
      run: |
        cd server
        npm ci

    # Set up Backend Environment
    - name: Set up Backend Environment
      run: |
        cd server
        touch .env
        echo "${{ secrets.BUILD_ENV }}" > .env

   
       

    # Install Frontend Dependencies
    - name: Install Frontend Dependencies
      run: |
        cd public
        npm ci

    # Set up Frontend Environment
    # - name: Set up Frontend Environment
    #   run: |
    #     cd public 
    #     touch .env
    #     echo "${{ secrets.FRONTEND_ENV }}" > .env

    # # Build Frontend
    # - name: Build Frontend
    #   run: |
    #     cd public
    #     npm run build

    # # Run Frontend Tests
    # - name: Run Frontend Tests
    #   run: |
    #     cd public
    #     npm start

    # Additional Steps (if needed)

    - name: Cleanup
      run: |
        # Any cleanup steps if needed
